### ISSUE TITLE
CMAKE_CXX_STANDARD 23 when compiling with gcc makes clang-tidy fail

### ISSUE THREAD

**Issue by fgallegosalido** [aminya/project_options#113]
The C++23 standard initial support was in CMake 3.20. However, there seems to be some disagreement between GCC and Clang regarding the standard compiler flags.

For instance, while GCC accepts both `-std=c++23` and `-std=c++2b`, Clang only accepts `-std=c++2b`. For this reason, when trying to enable clang-tidy and C++23 while compiling with GCC, Clang fails with a message indicating that the flag `-std=c++23` does not exist.

I'm not sure if it's worthy fixing this, as Clang will eventually add the correct flag. Meanwhile, it prevents the user from enabling clang-tidy while compiling using GCC and C++23.

**Comment by fgallegosalido** [comment]
It's true that C++23 is not released yet (it should be called C++2b to be precise). However, many compilers have already implemented many accepted features, and I like to experiment with them in my personal projects. Not being able to do so using this CMake library is not ideal for me.

Maybe an option to add custom extra arguments to clang-tidy could be implemented. However, if you feel like this doesn't add any value, feel free to close this issue.

**Comment by aminya** [comment]
The issue with adding custom logic is that once the standard is released, those flags will become invalid or deprecated. So, I recommend you to patch `project_options` temporarily if you wanna do that.
