### ISSUE TITLE
Disable linting/checks on specific target

### ISSUE THREAD

**Issue by ryanseipp** [aminya/project_options#132]
The project as a whole is using v0.22.4 and calls `dynamic_project_options` with `ENABLE_CONAN` and `CONAN_OPTIONS` parameters. CMake is generating a debug build and developer mode is on.

I have a library within my project that utilizes protobuf/grpc and generates a lot of code. This library never links against `project_options` or `project_warnings`. That library is then linked to the executable that requires it using `target_link_system_libraries(exe PRIVATE protoObjects)`. However, I still get tons of errors against that generated code. The sanitizers/linters would be great to use across the rest of the app, but not this single target. As such, I'm hoping there's an option, workaround, or otherwise to be able to prevent static analysis against this target.

**Comment by ryanseipp** [comment]
I've found the solution to this. Didn't realize at first that this was functionality and properties that CMake enables by default when a target is created after `CMAKE_CXX_CPPCHECK` is defined. The solution is to unset the `CXX_CPPCHECK` and `CXX_CLANG_TIDY` properties on the target using
```cmake
set_property(TARGET protoObjects PROPERTY CXX_CPPCHECK)
set_property(TARGET protoObjects PROPERTY CXX_CLANG_TIDY)
```

There may be an opportunity to improve this experience by exporting a function to disable static analysis on a target, but as my issue has a solution, I'll close this.

**Comment by aminya** [comment]
Thanks! Would you like to add your comment to the readme?
