### ISSUE TITLE
The project_options should only FetchContents of other repos with stable versions tags

### ISSUE THREAD

**Issue by ClausKlein** [aminya/project_options#156]
Some of the other `CMake` git repos used by this project have no stable git tag.

- Would it be possible to change this?
- Would it also possible to document this dependencies too?
- Is it possible to always use `FetchContent_MakeAvailable()`?
- see https://github.com/ClausKlein/project_options/pull/5#pullrequestreview-1114348013

i.e.
```cmake
  # in PackageProject.cmake
  # download ForwardArguments
  FetchContent_Declare(
    _fargs
    URL https://github.com/polysquare/cmake-forward arguments/archive/8c50d1f956172edb34e95efa52a2d5cb1f686ed2.zip)

# in VCEnvironment.cmake
# Using Windows MSVC toolchain
FetchContent_Declare(
        _msvc_toolchain URL "https://github.com/aminya/Toolchain/archive/95891a1e28a406ffb22e572f3ef24a7a8ad27ec0.zip")
```

**Comment by ClausKlein** [comment]
@lefticus @aminya please note this brand new `CMake v3.24 option` I want to use:
```bash
cmake -DCMAKE_PROJECT_TOP_LEVEL_INCLUDES=$PWD/mycomp_provider.cmake -S . -B build -G Ninja -Wno-dev
```

**Comment by ClausKlein** [comment]
see too https://discourse.cmake.org/t/fetchcontent-vs-vcpkg-conan/6578

**Comment by aminya** [comment]
Since v0.26.1 all the fetch contents are based on a stable tag
