### ISSUE TITLE
Utilities.cmake/is_verbose function and conan `OUTPUT_QUIET` dosen't work

### ISSUE THREAD

**Issue by FeignClaims** [aminya/project_options#158]
in src/Utilities.cmake, `"CMAKE_MESSAGE_LOG_LEVEL" STREQUAL...` should be `"${CMAKE_MESSAGE_LOG_LEVEL}"  STREQUAL...`.

in src/Conan.cmake, the `else()` branch should just set `OUTPUT_QUIET` to nothing.

https://github.com/aminya/project_options/blob/939d083e03f58396784f76efdc01cab2b936aa64/src/Utilities.cmake#L132-L145

https://github.com/aminya/project_options/blob/939d083e03f58396784f76efdc01cab2b936aa64/src/Conan.cmake#L55-L60

**Comment by aminya** [comment]
Pull requests are welcome
