### ISSUE TITLE
Can no longer include project_options as a submodule

### ISSUE THREAD

**Issue by SK83RJOSH** [aminya/project_options#161]
I prefer to explicitly depend on project_options as a submodule and add it using `add_directory`. Unfortunately, this seems to have broken with #154 as I now get the following error:

```
[cmake] CMake Error at cmake/project_options/src/Common.cmake:5 (include):
[cmake]   include could not find requested file:
[cmake] 
[cmake]     /PreventInSourceBuilds.cmake
```

**Comment by SK83RJOSH** [comment]
I'm using `project_options()` and my setup is [here](https://github.com/SK83RJOSH/cblend/blob/main/CMakeLists.txt). If you clone that repository, update the switch the submodule to use main, and try to configure with an empty cache you'll be able to reproduce.

**Comment by ClausKlein** [comment]
I got it. this patch helps:
```diff
diff --git a/src/Common.cmake b/src/Common.cmake
index 499992f..20f726a 100644
--- a/src/Common.cmake
+++ b/src/Common.cmake
@@ -1,7 +1,16 @@
 include_guard()

+macro(set_project_options_src_dir)
+  get_directory_property(LISTFILE_STACK LISTFILE_STACK)
+  list(POP_BACK LISTFILE_STACK _LIST_FILE)
+  cmake_path(GET _LIST_FILE PARENT_PATH ProjectOptions_SRC_DIR)
+endmacro()
+
 # Common project settings run by default for all the projects that call `project_options()`
 macro(common_project_options)
+  set_project_options_src_dir()
+  message(DEBUG "${ProjectOptions_SRC_DIR}")
+
   include("${ProjectOptions_SRC_DIR}/PreventInSourceBuilds.cmake")
   assure_out_of_source_builds()

```

**Comment by aminya** [comment]
Thanks. Could you update #163 or make a new PR with this patch?
@SK83RJOSH @ClausKlein

**Comment by SK83RJOSH** [comment]
@ClausKlein ingenuous solution, much appreciated 😄

@aminya I'm away from my PC at the moment, but if Claus doesn't beat me to it I can amend this PR in a little bit.

Thank you both for the help 🤘
