### ISSUE TITLE
update to stable tagged version of WindowsToolchain

### ISSUE THREAD

**Issue by ClausKlein** [aminya/project_options#165]
### We are not allowed to fetch contents from internet on our company CI!

So the call to `msvc_toolchain() `fails on our Windows build while using `project_options`.

Too, I can't understand why you download `ninja` and other tools in this call?

**IMHO**, this should be done with `setup-cpp`?

**Comment by aminya** [comment]
Feel free to add an option for it in a PR.

**Comment by ClausKlein** [comment]
I so Not understand  the Toolchain and it is wrong to download exe  fils while Build?
You are also using an untaged version!

**Comment by aminya** [comment]
Since the windows toolchain is trying to be self-contained, I don't have any complaints about it. If you already have ninja installed, it should probably skip downloading.

**Comment by ClausKlein** [comment]
There is at leased one bug in our `Toolchain` version you use!

see https://github.com/MarkSchofield/WindowsToolchain/commit/b2498022f3fee194c8cbe687acb9a8e695558273

**Comment by ClausKlein** [comment]
please note https://github.com/aminya/project_options/issues/156 too

**Comment by aminya** [comment]
I'll wait for the latest updates on the Window toolchain. 
https://github.com/MarkSchofield/WindowsToolchain/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc
