### ISSUE TITLE
Doxygen options overwrite

### ISSUE THREAD

**Issue by Subtixx** [aminya/project_options#177]
In the CMake for Doxygen there is a block that overwrites custom settings:

https://github.com/aminya/project_options/blob/283c25fdd782f2f3e754a09488175e910893b180/src/Doxygen.cmake#L15-L21

If I don't want call graphs or caller graphs, there is currently no way to disable it since it always gets overwritten by those values.

Can you please add a defined if statement around it so if it is already set, that project_options does not touch the set setting?

**Comment by aminya** [comment]
Fixed by #178
