### ISSUE TITLE
target_find_dependencies with COMPONENT

### ISSUE THREAD

**Issue by tomdavsmi** [aminya/project_options#251]
I've checked the documentation over and I can't quite see a way to combine the COMPONENTS argument of find_package with target_find_dependencies. 

For example:
```cmake
find_package(Qt6 CONFIG REQUIRED COMPONENTS Widgets)
```
works, as does
```cmake
target_find_dependencies(foo PRIVATE_CONFIG Qt6)
```

But the target_find_dependencies approach means that I can't then go on to write Qt6::Widgets in my call to target_link_system_libraries. 

Is this intentional and there's a nuance I've missed/don't understand yet?

## Upvote & Fund

@aminya is using [Polar.sh](https://polar.sh/aminya) so you can upvote and help fund this issue. The funding is received once the issue is completed & confirmed by you.

Thank you in advance for helping prioritize & fund our backlog!

<br/>

<a href="https://polar.sh/aminya/project_options/issues/251">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/aminya/project_options/issues/251/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/aminya/project_options/issues/251/pledge.svg">
</picture>
</a>

**Comment by aminya** [comment]
Thanks for the ticket. This is a known issue, and we should fix it.

As a workaround, you can always directly use `find_package` and set the `PUBLIC_DEPENDENCIES` manually in `package_project`

**Comment by tomdavsmi** [comment]
Thanks for the response - that workaround is fine by me. 

One question though - for manually setting `PUBLIC_DEPENDENCIES` do I just the base name (e.g. Qt6) or the qualified component name (e.g. Qt6::Widgets).

Thanks again - I'm happy for this to be closed unless you want to keep this open to track.
