### ISSUE TITLE
feature request: remove redundant clang-tidy arguments to avoid possible bugs

### ISSUE THREAD

**Issue by FeignClaims** [aminya/project_options#272]
According to [the cmake implementation code](https://gitlab.kitware.com/cmake/cmake/-/blob/8733dcd11588f2d9eb0bddc8af8a6db7a2e9eba8/Source/cmcmd.cxx#L370-416), especially [this comment](https://gitlab.kitware.com/cmake/cmake/-/blob/8733dcd11588f2d9eb0bddc8af8a6db7a2e9eba8/Source/cmcmd.cxx#L382-389), clang-tidy can normally accept all compiler command line arguments after `--`, so there's redundant work in [StaticAnalyzers.cmake](https://github.com/aminya/project_options/blob/8da3903ce539ae7be53c1ee4cb17d38d29656f58/src/StaticAnalyzers.cmake).

This, however, might require a difficult review of the code.

## Upvote & Fund

@aminya is using [Polar.sh](https://polar.sh/aminya) so you can upvote and help fund this issue. The funding is received once the issue is completed & confirmed by you.

Thank you in advance for helping prioritize & fund our backlog!

<br/>

<a href="https://polar.sh/aminya/project_options/issues/272">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/aminya/project_options/issues/272/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/aminya/project_options/issues/272/pledge.svg">
</picture>
</a>

**Comment by aminya** [comment]
I don't think we can fix it in project_options.

I opened an issue upstream:
https://gitlab.kitware.com/cmake/cmake/-/issues/26283

I tried passing this, but it didn't help
```
  CLANG_TIDY_EXTRA_ARGUMENTS
  "-extra-arg=-Wno-unknown-warning-option;-extra-arg=-Wno-error=unused-command-line-argument;-extra-arg=-Wno-unused-command-line-argument;-extra-arg=-Qunused-arguments"
```
